added search
Kettengeschwindigkeit/Junior-Frontend-Developer-React-Module-Homework pull request #3
Opened 2022-08-25 16:39 UTC by Kettengeschwindigkeit

added input tag and handleSearchByName arrow function

2022-08-26 16:43 UTC, Kettengeschwindigkeit commented on src/app/components/users.jsx
> +                : users;
Нужно наверное, еще trim() было добавить, забыл...

2022-08-29 10:37 UTC, ArturZhitkovich requested changes

2022-08-29 10:37 UTC, ArturZhitkovich commented on src/app/components/users.jsx
>      const [professions, setProfession] = useState();
Я советую ставить начальное значение

2022-08-29 10:37 UTC, ArturZhitkovich commented on src/app/components/users.jsx
>      const [selectedProf, setSelectedProf] = useState();
Тоже самое

2022-08-29 10:37 UTC, ArturZhitkovich commented on src/app/components/users.jsx
>      useEffect(() => {
Объедени эти useEfect в один

2022-08-29 10:37 UTC, ArturZhitkovich commented on src/app/components/users.jsx
> +        console.log(users.length);
зачем console.log

2022-08-29 10:37 UTC, ArturZhitkovich commented on src/app/components/users.jsx
> +                : users;
ДА, trim почит всегда используется

2022-08-29 10:37 UTC, ArturZhitkovich commented on src/app/components/users.jsx
> +                            <ul>
Это что ?

2022-08-30 08:17 UTC, ArturZhitkovich approved these changes

2022-08-30 08:17 UTC, ArturZhitkovich commented on src/app/components/users.jsx
>          setSelectedProf();
setSelectedProf(null) 

Если у тебя в стейте будет объект, и ты не знаешь его начальное значение, тогда это будет null

2022-09-01 06:02 UTC, merged